name: PDF Generation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libffi-dev gcc

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install PyMuPDF  # Install fitz module

    - name: Execute py script
      env:
        SOME_SECRET: ${{ secrets.SOME_SECRET }}
      run: python pypdf.py
          
    - name: Check for changes
      run: git diff-index --quiet HEAD || (git add -A && git commit -m "updated logs" --allow-empty)
      shell: bash
      working-directory: ${{ github.workspace }}

    - name: Push changes
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
